# Generated by Django 4.2.1 on 2023-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamesession",
            options={},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={},
        ),
        migrations.AlterModelOptions(
            name="village",
            options={},
        ),
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("game_session", "nickname")},
        ),
    ]
