# Generated by Django 4.2.1 on 2023-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_created_at_gamesession_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='clay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='morale',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='village',
            name='wood',
            field=models.IntegerField(default=0),
        ),
    ]
