# Generated by Django 4.2.1 on 2023-05-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('game', '0004_village_clay_village_iron_village_morale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='barracks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.barracks'),
        ),
        migrations.AddField(
            model_name='village',
            name='clay_pit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.claypit'),
        ),
        migrations.AddField(
            model_name='village',
            name='granary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.granary'),
        ),
        migrations.AddField(
            model_name='village',
            name='iron_mine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.ironmine'),
        ),
        migrations.AddField(
            model_name='village',
            name='sawmill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.sawmill'),
        ),
        migrations.AddField(
            model_name='village',
            name='town_hall',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.townhall'),
        ),
    ]
