# Generated by Django 4.2.1 on 2023-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_village_clay_village_iron_village_morale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='barracks_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='village',
            name='clay_pit_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='village',
            name='granary_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='village',
            name='iron_mine_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='village',
            name='sawmill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='village',
            name='town_hall_level',
            field=models.IntegerField(default=1),
        ),
    ]
