# Generated by Django 4.2.1 on 2023-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gamesession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='last_resources_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='clay',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='village',
            name='iron',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='village',
            name='wood',
            field=models.IntegerField(default=150),
        ),
    ]
