# Generated by Django 4.2.1 on 2023-06-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_village_last_resources_update_alter_village_clay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='granary_level',
            new_name='warehouse_level',
        ),
    ]
