# Generated by Django 4.2.1 on 2023-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_granary_level_village_warehouse_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='clay',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='village',
            name='iron',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='village',
            name='wood',
            field=models.FloatField(default=150),
        ),
    ]
