# Generated by Django 4.2.1 on 2023-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_village_clay_alter_village_iron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
