# Generated by Django 4.2.1 on 2023-06-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
