# Generated by Django 4.2.1 on 2023-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_village_units_archer_village_units_axeman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_code',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
