# Generated by Django 4.2.1 on 2023-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_gamesession_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='are_units_training',
            field=models.BooleanField(default=False),
        ),
    ]
