# Generated by Django 4.2.1 on 2023-06-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_village_are_units_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='units_archer',
            new_name='archer_count',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='units_axeman',
            new_name='axeman_count',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='units_spearman',
            new_name='spearman_count',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='units_swordman',
            new_name='swordsman_count',
        ),
    ]
