# Generated by Django 4.2.2 on 2023-06-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0018_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='game_session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
            preserve_default=False,
        ),
    ]
