# Generated by Django 4.2.1 on 2023-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attacker_strenght',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_strenght',
            field=models.FloatField(default=0),
        ),
    ]
